name: Deploy no Google Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/streamlit-repo/streamlit-app:${{ github.sha }}

    steps:
      # 🔹 Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🔹 Configurar autenticação com Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 🔹 Configurar o Google Cloud SDK
      - name: Configurar gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth configure-docker --quiet

      # 🔹 Construir a imagem Docker e enviar para o Google Artifact Registry
      - name: Construir e enviar imagem Docker
        run: |
          echo "Construindo a imagem Docker..."
          docker build -t $IMAGE_NAME .

          echo "Enviando a imagem para o Google Artifact Registry..."
          docker push $IMAGE_NAME

      # 🔹 Fazer o deploy no Cloud Run
      - name: Deploy no Cloud Run
        run: |
          echo "Realizando deploy no Cloud Run..."
          gcloud run deploy streamlit-app \
            --image=$IMAGE_NAME \
            --region=us-central1 \
            --platform=managed \
            --port=5432 \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_NAME=${{ secrets.DB_NAME }}"

      # 🔹 Mostrar a URL do serviço
      - name: Exibir URL do serviço
        run: |
          echo "Obtendo a URL do serviço..."
          gcloud run services describe streamlit-app --region=us-central1 --format 'value(status.url)'
